fixed scoring and added comments

diff --git a/src/scoring_loop b/src/scoring_loop
--- a/src/scoring_loop
+++ b/src/scoring_loop
@@ -1,6 +1,10 @@
 #!/bin/bash
 # scoring_loop by David Weinman <david@weinman.com>
 
+# grabs input / output pairs from the designated file ($INPT_OUTPT_FILE)
+# and scores the entries comparing the results to the refcalc's results
+# storing results in /tmp/scoring/answers. (forever loop)
+
 # This file is licensed under The DO WHAT THE FUCK YOU WANT TO License, see LICENSE for details.
 
 FIRST_CWD=$(pwd)
@@ -10,7 +14,7 @@ cd $SCOREDIRNAME
 
 touch /tmp/calc_in_out
 INPT_OUTPT_FILE="/tmp/calc_in_out"
-ERRLOG="./scoring_errlog.txt"
+ERRLOG="$FIRST_CWD/$SCOREDIRNAME/scoring_errlog.txt"
 LINES_READ_IN_OUT="$(wc -l $INPT_OUTPT_FILE | awk '{print $(NF - 1)}')"
 
 while [ 0 ]; do
@@ -22,7 +26,6 @@ while [ 0 ]; do
     # check if the scorebot has been signaled to stop
     if [ "$(sed -n "$LINES_READ_IN_OUT p" $INPT_OUTPT_FILE)" == "game completed" ]; then
 
-      cleanup
       exit
 
     fi
@@ -51,15 +54,15 @@ while [ 0 ]; do
 
     NOW=$(date +%m-%d--%H:%M:%S)
     PRETTY_INPUT="$(blacklist_replace "$INPUT")"
-    # if the refcalc output and the given output are the same, award appropriate points
+    # else if the refcalc output and the given output are the same, award appropriate points
     if [ $(equal "$REFCALC_OUTPUT" "$OUTPUT" 2> $ERRLOG) == "True" ]; then
 
     # defending team gets points and attacking team gets no points
       DEFENDING_PTS="$(echo "$DEFENDING_PTS + 10" | /usr/bin/refcalc/calc)"
       echo "$NOW:(INPUT: $PRETTY_INPUT, OUTPUT: $OUTPUT) : DEFENDING TEAM'S POINTS = $DEFENDING_PTS ATTACKING TEAM'S POINTS = $ATTACKING_PTS" >> /tmp/scoring/answers
 
-    # else if both the refcalc and the defending team gave errors, defending team gets pts
-    elif [[ ( "$REFCALC_STDERR" != "" ) && $(echo "$OUTPUT" | grep -q -i 'error') ]]; then
+    # if both the refcalc and the defending team gave errors, defending team gets pts
+    elif [[ "$REFCALC_STDERR" != "" && $(echo "$OUTPUT" | grep -q -i "error"; echo $?) = "0" ]]; then
 
     # defending team gets points and attacking team gets no points
       DEFENDING_PTS="$(echo "$DEFENDING_PTS + 10" | /usr/bin/refcalc/calc)"
@@ -88,6 +91,7 @@ while [ 0 ]; do
     # reset current time
     NOW=""
 
+  # if scoring_loop has read all lines in file currently, it goes to sleep for a little while
   else
 
     sleep 2
@@ -98,6 +102,5 @@ done
 
 SRVR_PID=""
 cd $FIRST_CWD
-
 
 
